name = "Paper"
license = "MIT"
licenselink = "https://github.com/nanxiaobei/hugo-paper/blob/main/LICENSE"
description = "A simple, clean, flexible Hugo theme"
homepage = "https://mosaphir.github.io/paper/"
demosite = "https://mosaphir.github.io/paper"
tags = ["Responsive", "Simple", "Clean", "Light", "White", "Blog"]
features = ["Responsive", "One Column", "Blog"]
min_version = "0.57.1"

[author]
  name = "cyberxbd"
  homepage = "https://t.me/cyberxbd"
