name = "Paper"
license = "MIT"
licenselink = "https://github.com/nanxiaobei/hugo-paper/blob/main/LICENSE"
description = "A simple, clean, flexible Hugo theme"
homepage = "https://mosaphir.github.io/paper/"
demosite = "https://mosaphir.github.io/paper"
tags = ["Responsive", "Simple", "Clean", "Light", "White", "Blog"]
features = ["Responsive", "One Column", "Blog"]
min_version = "0.57.1"

[author]
  name = "cyberxbd"
  homepage = "https://t.me/cyberxbd"


[services]
  [services.disqus]
    shortname = 'sobkiso'     # use disqus comments

[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'YOUR_GITHUB_ID'                 # github.com/YOUR_GITHUB_ID
  instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  threads = '@YOUR_THREADS_ID'              # threads.net/@YOUR_THREADS_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'YOUR_NAME'
  bio = 'YOUR_BIO'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://raw.githubusercontent.com/mosaphir/w/main/unnamed.png?token=GHSAT0AAAAAACXK4C2O4E6JYWN4UTSOFSDMZXD2ARQ'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
#  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  direction = "rtl"                         # RTL support for Right-to-left languages

  # giscus
[params.giscus]
  repo = 'mosaphir/paper'                 # see https://giscus.app for more details
  repoId = 'R_kgDOMvWppw'
  category = 'General'
  categoryId = 'DIC_kwDOMvWpp84CibkY'
  mapping = 'pathname'
  theme = 'light'
  lang = 'en-US'
